[project]
name = "qwen3-tts-post-training"
version = "0.1.0"
description = "GRPO post-training pipeline for Qwen3-TTS CustomVoice (Cyrene)"
readme = "README.md"
authors = [
    { name = "FelysNeko" }
]
requires-python = ">=3.12"
dependencies = [
    "torch==2.8.0",
    "torchvision==0.23.0",
    "torchaudio==2.8.0",
]

[[tool.uv.index]]
name = "pytorch-cu128"
url = "https://download.pytorch.org/whl/cu128"
explicit = true

[tool.uv.sources]
torch = { index = "pytorch-cu128" }
torchvision = { index = "pytorch-cu128" }
torchaudio = { index = "pytorch-cu128" }

[build-system]
requires = ["uv_build>=0.12.5,<0.13.0"]
build-backend = "uv_build"
